from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os
import re

class ExamFormatter:
    def __init__(self):
        pass

    def create_exam_docx(self, exam_content: str, filename: str = "Generated_Exam.docx") -> str:
        """
        Parses the Markdown-like exam content and creates a formatted DOCX.
        Returns the absolute path to the file.
        """
        doc = Document()
        
        # Title
        title = doc.add_heading('GEOTECHNICAL ENGINEERING EXAM', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph("Department of Civil Engineering").alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph("_" * 50).alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Content Parsing
        # Assumes content has **Bold** or markdown headers
        lines = exam_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line: continue
            
            if line.startswith("# ") or line.startswith("**Question"):
                # Header
                p = doc.add_paragraph()
                run = p.add_run(line.replace("# ", "").replace("**", ""))
                run.bold = True
                run.font.size = Pt(12)
            elif line.startswith("- "):
                 doc.add_paragraph(line[2:], style='List Bullet')
            else:
                doc.add_paragraph(line)
                
        # Footer
        section = doc.sections[0]
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = "Generated by Geotechnical AI Council"
        
        # Save
        # Ensure directory exists
        output_dir = "outputs"
        os.makedirs(output_dir, exist_ok=True)
        
        full_path = os.path.abspath(os.path.join(output_dir, filename))
        doc.save(full_path)
        return full_path

if __name__ == "__main__":
    f = ExamFormatter()
    print(f.create_exam_docx("Sample Exam\n\n**Question 1**\nCalculate stuff."))
